pipeline {
    agent {
        label 'nodejs'
    }
    stages {
        stage('install dependencies') {
            steps {
                dir ('exchange-cli') {
                    sh "npm install"
                }
            }
        }
        stage('build') {
            steps {
                dir ('exchange-cli') {
                    sh "npm run build"   
                }
            }
        }
        stage('unit tests') {
            steps {
                dir ('exchange-cli') {
                    sh "npm run test:unit"
                }
            }
        }
        stage('functional tests') {
            steps {
                dir ('exchange-cli') {
                    sh "npm run test:functional"
                }
            }
        }
    }
}
